name: CI

on:
  pull_request:
  push:

jobs:
  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    container: node:18
    timeout-minutes: 60
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

  go:
    name: Go
    runs-on: ubuntu-latest
    container: golang:1
    timeout-minutes: 60
    defaults:
      run:
        working-directory: ./go
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: Test
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic -failfast ./...